# Generated by Django 5.1.4 on 2026-05-15 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='project',
            new_name='projects_pr_slug_042165_idx',
            old_name='projects_pr_slug_95c4b5_idx',
        ),
        migrations.RenameIndex(
            model_name='project',
            new_name='projects_pr_owner_i_5cc2bd_idx',
            old_name='projects_pr_owner_i_aa7b86_idx',
        ),
        migrations.RenameIndex(
            model_name='project',
            new_name='projects_pr_created_6b02e3_idx',
            old_name='projects_pr_created_c5c7da_idx',
        ),
        migrations.RenameIndex(
            model_name='projectmember',
            new_name='projects_pr_project_7e6765_idx',
            old_name='projects_pr_project_a4b4b8_idx',
        ),
        migrations.RenameIndex(
            model_name='projectmember',
            new_name='projects_pr_user_id_5f83f5_idx',
            old_name='projects_pr_user_id_5e921d_idx',
        ),
    ]
