# Generated by Django 5.1.4 on 2026-05-15 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='activitylog',
            new_name='tasks_activ_project_8ab304_idx',
            old_name='tasks_activ_project_bc6e61_idx',
        ),
        migrations.RenameIndex(
            model_name='activitylog',
            new_name='tasks_activ_task_id_ed12e0_idx',
            old_name='tasks_activ_task_id_ef5ef7_idx',
        ),
        migrations.RenameIndex(
            model_name='activitylog',
            new_name='tasks_activ_actor_i_5be99a_idx',
            old_name='tasks_activ_actor_i_36a8bb_idx',
        ),
        migrations.RenameIndex(
            model_name='activitylog',
            new_name='tasks_activ_verb_16a791_idx',
            old_name='tasks_activ_verb_741d69_idx',
        ),
        migrations.RenameIndex(
            model_name='attachment',
            new_name='tasks_attac_task_id_f43e53_idx',
            old_name='tasks_attac_task_id_dae80e_idx',
        ),
        migrations.RenameIndex(
            model_name='attachment',
            new_name='tasks_attac_uploade_3ab901_idx',
            old_name='tasks_attac_uploade_e78e51_idx',
        ),
        migrations.RenameIndex(
            model_name='task',
            new_name='tasks_task_project_b78682_idx',
            old_name='tasks_task_project_616d9d_idx',
        ),
        migrations.RenameIndex(
            model_name='task',
            new_name='tasks_task_project_7f8813_idx',
            old_name='tasks_task_project_d86a37_idx',
        ),
        migrations.RenameIndex(
            model_name='task',
            new_name='tasks_task_assigne_42029e_idx',
            old_name='tasks_task_assigne_292d18_idx',
        ),
        migrations.RenameIndex(
            model_name='task',
            new_name='tasks_task_due_dat_bce847_idx',
            old_name='tasks_task_due_dat_9e6958_idx',
        ),
        migrations.RenameIndex(
            model_name='task',
            new_name='tasks_task_created_be1ba2_idx',
            old_name='tasks_task_created_4eac44_idx',
        ),
        migrations.RenameIndex(
            model_name='taskcomment',
            new_name='tasks_taskc_task_id_3f97e8_idx',
            old_name='tasks_taskc_task_id_a5f7cd_idx',
        ),
        migrations.RenameIndex(
            model_name='taskcomment',
            new_name='tasks_taskc_author__763a66_idx',
            old_name='tasks_taskc_author__8572bd_idx',
        ),
    ]
